// src/resources/assets/js/components/Card.jsx
import React from 'react'

const Card = () => {
  return (
    <div className="grid-item card_wrapper">
      <div className="card_container">
        <img className="profile_icon" src="" alt="" />
        <div className="card_container_right">
          <p className="profile_name">Natsuya Yada</p>
          <p className="shelf_name">アメリカンライフスタイル</p>
        </div>
      </div>
      <img className="card_eyecatch" src="" alt="" />
      <div className="card_container">
        <p className="card_title">かっこよすぎるバーベキューテク6選 - アウトドア初心者のパパでも簡単!</p>
      </div>
      <a className="save_button" href="#">シェルフへ</a>
    </div>
  );
}

export default Card

// src/resources/assets/js/components/CardComponent.vue
<template>
  <div class="grid-item card_wrapper">
    <div class="card_container">
      <img class="profile_icon" src="" alt="">
      <div class="card_container_right">
        <p class="profile_name">Natsuya Yada</p>
        <p class="shelf_name">アメリカンライフスタイル</p>
      </div>
    </div>
    <img class="card_eyecatch" src="" alt="">
    <div class="card_container">
      <p class="card_title">かっこよすぎるバーベキューテク6選 - アウトドア初心者のパパでも簡単!</p>
    </div>
    <a class="save_button" href="#">シェルフへ</a>
  </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style>
</style>
