// src/resources/assets/js/components/ModalComponent.vue
<template>
<div class="modal_content_wrapper">
      <div class="modal_content_container small_container">
        <div class="modal_lists_header">
          <p>Natsuya Yadaのフォローしている</p>
          <h3>ユーザー</h3>
        </div>
        <ul class="modal_lists_body">

            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>
            <li class="modal_list">
              ライフスタイル
              <span class="modal_list_attach">2 matches</span>
            </li>

        </ul>
      </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style>
</style>

// src/resources/assets/js/components/Modal.jsx
import React from 'react'

const Modal = () => {
  return (
    <div className="modal_content_wrapper">
      <div className="modal_content_container small_container">
        <div className="modal_lists_header">
          <p>Natsuya Yadaのフォローしている</p>
          <h3>ユーザー</h3>
        </div>
        <ul className="modal_lists_body">
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
          <li className="modal_list">
            ライフスタイル
            <span className="modal_list_attach">2 matches</span>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Modal
