// src/resources/assets/js/components/ShelfCardComponent.vue
<template>
  <div class="grid-item card_wrapper">
    <div class="card_container">
        <p class="main_shelf_name">シェルフ</p>
        <p class="shelf_col_num"><span class="num">20</span>Collections</p>
    </div>
    <img class="picked_eyecatchs" src="" alt="">
  </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style>
</style>

// src/resources/assets/js/components/ShelfCard.jsx
import React from 'react'

const ShelfCard = () => {
  return (
    <div className="grid-item card_wrapper">
      <div className="card_container">
          <p className="main_shelf_name">シェルフ</p>
          <p className="shelf_col_num"><span className="num">20</span>Collections</p>
      </div>
      <img className="picked_eyecatchs" src="" alt="" />
    </div>
  );
};

export default ShelfCard
