// src/resources/assets/js/components/ShelfComponent.vue
<template>
<div>
  <header-component></header-component>
  <main class="clearfix">
      <div class="sub_header shelf">
        <h2 class="shelf_title">SHELF</h2>
        <p class="shelf_col_num">20 Collections</p>
      </div>
      <div class="grid">
        <card-component></card-component>
        <card-component></card-component>
        <card-component></card-component>
        <card-component></card-component>
      </div>
  </main>
  <footer-component></footer-component>
</div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

// src/resources/assets/js/components/Shelf.jsx
import React from 'react'
import Header from './Header'
import ShelfCard from './ShelfCard'
import Footer from './Footer'

const Shelf = () => {
  return (
    <Header />
    <main className="clearfix">
      <div className="sub_header shelf">
        <h2 className="shelf_title">SHELF</h2>
        <p className="shelf_col_num">20 Collections</p>
      </div>
      <div className="grid">
        <ShelfCard />
      </div>
    </main>
    <Footer />
  );
};

export default Shelf
