// src/resources/assets/js/components/SingleComponent.vue
<template>

  <div>
    <header-component></header-component>

    <main class="clearfix">

      <div class="single">
        <div class="card_wrapper">
          <div class="card_container">
            <img class="profile_icon" src="" alt="">
            <div class="card_container_right">
              <p class="profile_name">Natsuya Yada</p>
              <p class="shelf_name">アメリカンライフスタイル</p>
            </div>
          </div>
          <!-- <div class="card_eyecatch_bg"></div> -->
          <img class="card_eyecatch" src="" alt="">
          <div class="card_container">
            <p class="card_title">かっこよすぎるバーベキューテク6選 - アウトドア初心者のパパでも簡単!</p>
          </div>
          <a class="save_button" href="#">シェルフへ</a>
        </div>

        <div class="card_wrapper card_wrapper_next">
          <div class="card_container">
            <img class="profile_icon" src="" alt="">
            <div class="card_container_right">
              <p class="card_collectors"><a href="">Toshiaki Matsumuraさん</a>と<a href="">その他</a>が保存しました</p>
            </div>
          </div>
        </div>
      </div>

    </main>

    <footer-component></footer-component>
  </div>

</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

// src/resources/assets/js/components/Single.jsx
import React from 'react'
import Header from './Header'
import Footer from './Footer'

const Single = () => {
  return (
    <div>
      <Header />
      <main className="clearfix">
        <div className="single">
          <div className="card_wrapper">
            <div className="card_container">
              <img className="profile_icon" src="" alt="" />
              <div className="card_container_right">
                <p className="profile_name">Natsuya Yada</p>
                <p className="shelf_name">アメリカンライフスタイル</p>
              </div>
            </div>
            <img className="card_eyecatch" src="" alt="" />
            <div className="card_container">
              <p className="card_title">かっこよすぎるバーベキューテク6選 - アウトドア初心者のパパでも簡単!</p>
            </div>
            <a className="save_button" href="#">シェルフへ</a>
          </div>
          <div className="card_wrapper card_wrapper_next">
            <div className="card_container">
              <img className="profile_icon" src="" alt="" />
              <div className="card_container_right">
                <p className="card_collectors"><a href="">Toshiaki Matsumuraさん</a>と<a href="">その他</a>が保存しました</p>
              </div>
            </div>
          </div>
        </div>
    </main>
    <Footer />
    </div>
  );
};

export default Single
